name: panzer_maid
description: Panzer maid is your cybersecurity companion
version: 1.0.0
repository: https://github.com/cosmic-zip/panzer_maid

environment:
  sdk: ^3.4.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
