name: dartz
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/cosmic-zip/DartZ

environment:
  sdk: ^3.4.3

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
